import hmac
from datetime import date, datetime
from functools import lru_cache
from typing import Annotated, Any, Literal
from zoneinfo import ZoneInfo

from fastapi import Depends, FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.broker import Broker
from app.broker.alpaca import AlpacaBroker
from app.config import get_settings
from app.db import get_session
from app.domain.params import StrategyParams
from app.models import StrategyProfile
from app.models.enums import OpportunityStatus, RejectReason
from app.services import lab, safety, views
from app.services.trading import (
    DecisionError,
    accept_opportunity,
    close_position,
    reject_opportunity,
)

settings = get_settings()


@lru_cache
def get_broker() -> Broker:
    return AlpacaBroker.from_settings(settings)


DbSession = Annotated[Session, Depends(get_session)]
BrokerDep = Annotated[Broker, Depends(get_broker)]

app = FastAPI(title="Trading Advisor API", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def require_api_token(request: Request, call_next):
    """Once the API is reachable from the internet (API_TOKEN set), only the site may call it."""
    token = settings.api_token
    if token and request.url.path != "/health":
        sent = request.headers.get("x-api-token", "")
        if not hmac.compare_digest(sent.encode(), token.encode()):
            return JSONResponse({"detail": "Jeton d'API manquant ou invalide."}, status_code=401)
    return await call_next(request)


@app.get("/health")
def health(session: DbSession) -> dict[str, str]:
    try:
        session.execute(text("SELECT 1"))
        database = "ok"
    except SQLAlchemyError:
        database = "indisponible"
    return {"status": "ok", "database": database, "broker_env": settings.broker_env}


def market_today() -> date:
    return datetime.now(ZoneInfo("America/New_York")).date()


@app.get("/status")
def get_status(session: DbSession) -> dict[str, object]:
    """The permanent banner: active profile, PAPER, worker, data, monitor, trading allowed."""
    config = lab.active_config(session)
    profile = session.get(StrategyProfile, config.profile_id) if config.profile_id else None
    params = StrategyParams.from_dict(config.params)
    return {
        **safety.status(session, params, settings.starting_capital),
        "profile": profile.name if profile else None,
        "profile_version": config.version,
        "broker_env": settings.broker_env,
    }


@app.get("/dashboard")
def get_dashboard(session: DbSession) -> dict[str, object]:
    return views.dashboard(session, settings.starting_capital, market_today())


@app.get("/opportunities")
def get_opportunities(
    session: DbSession, status: OpportunityStatus | None = OpportunityStatus.PROPOSED
) -> list[dict[str, object]]:
    return views.opportunities(session, settings.starting_capital, status)


@app.get("/positions")
def get_positions(session: DbSession) -> dict[str, object]:
    return views.positions(session, market_today())


HistoryKind = Literal["closed", "expired", "assigned", "canceled", "rejected", "ignored"]
HistoryStrategy = Literal["put_credit_spread", "cash_secured_put", "covered_call", "shares"]


@app.get("/history")
def get_history(
    session: DbSession,
    kind: Annotated[list[HistoryKind] | None, Query()] = None,
    underlying: str | None = Query(default=None, max_length=16),
    strategy: HistoryStrategy | None = None,
    since: date | None = None,
    until: date | None = None,
) -> dict[str, object]:
    rows = views.history(
        session, views.HistoryFilter(tuple(kind or ()), underlying, strategy, since, until)
    )
    return {"rows": rows, "underlyings": views.history_underlyings(session)}


class AcceptRequest(BaseModel):
    # Generated by the client once per click, so a double submit sends a single order.
    idempotency_key: str = Field(min_length=8, max_length=64)
    # Net credit per share; defaults to the screener's mid.
    limit_price: float | None = Field(default=None, gt=0)


class RejectRequest(BaseModel):
    idempotency_key: str = Field(min_length=8, max_length=64)
    reason: RejectReason
    note: str | None = Field(default=None, max_length=500)


@app.post("/opportunities/{opportunity_id}/accept")
def accept(
    opportunity_id: int, body: AcceptRequest, session: DbSession, broker: BrokerDep
) -> dict[str, object]:
    try:
        position = accept_opportunity(
            session,
            broker,
            opportunity_id,
            body.idempotency_key,
            settings.starting_capital,
            body.limit_price,
        )
    except DecisionError as exc:
        raise HTTPException(exc.status_code, str(exc)) from exc
    order = position.orders[0] if position.orders else None
    return {
        "position_id": position.id,
        "position_status": position.status.value,
        "order_status": order.status.value if order else None,
        "limit_price": float(order.limit_price) if order and order.limit_price else None,
    }


@app.post("/opportunities/{opportunity_id}/reject")
def reject(opportunity_id: int, body: RejectRequest, session: DbSession) -> dict[str, object]:
    try:
        decision = reject_opportunity(
            session, opportunity_id, body.idempotency_key, body.reason, body.note
        )
    except DecisionError as exc:
        raise HTTPException(exc.status_code, str(exc)) from exc
    return {"decision_id": decision.id, "reason": body.reason.value}


class CloseRequest(BaseModel):
    idempotency_key: str = Field(min_length=8, max_length=48)


@app.post("/positions/{position_id}/close")
def close(
    position_id: int, body: CloseRequest, session: DbSession, broker: BrokerDep
) -> dict[str, object]:
    try:
        order = close_position(session, broker, position_id, body.idempotency_key)
    except DecisionError as exc:
        raise HTTPException(exc.status_code, str(exc)) from exc
    return {
        "position_id": order.position_id,
        "position_status": order.position.status.value,
        "order_status": order.status.value,
        "limit_price": float(order.limit_price) if order.limit_price else None,
    }


# --- settings lab: profiles and backtests ------------------------------------------------------


def _lab(call, session: Session):
    """Run a lab service call and commit, turning its refusals into HTTP errors."""
    try:
        out = call()
    except lab.LabError as exc:
        session.rollback()
        raise HTTPException(exc.status_code, str(exc)) from exc
    session.commit()
    return out


class ProfileCreate(BaseModel):
    name: str = Field(min_length=1, max_length=80)
    description: str | None = Field(default=None, max_length=500)
    params: dict[str, Any] = Field(default_factory=dict)
    # Start from this profile's parameters; `params` then holds only the changes.
    copy_from: int | None = None


class ProfileUpdate(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=80)
    description: str | None = Field(default=None, max_length=500)
    params: dict[str, Any] | None = None
    # Required to (re)activate a profile whose backtest lost money or broke its drawdown limit.
    confirm_risk: bool = False


class ActivateRequest(BaseModel):
    confirm_risk: bool = False


@app.get("/profiles")
def get_profiles(session: DbSession) -> dict[str, object]:
    return _lab(lambda: lab.list_profiles(session), session)


def _profile_out(session: Session, profile) -> dict[str, object]:
    return lab.profile_view(
        profile, lab.active_config(session).profile_id, lab.risk_verdict(session, profile)
    )


@app.post("/profiles")
def create_profile(body: ProfileCreate, session: DbSession) -> dict[str, object]:
    def call():
        profile = lab.create_profile(
            session, body.name, body.description, body.params, body.copy_from
        )
        return _profile_out(session, profile)

    return _lab(call, session)


@app.put("/profiles/{profile_id}")
def update_profile(profile_id: int, body: ProfileUpdate, session: DbSession) -> dict[str, object]:
    def call():
        profile = lab.update_profile(
            session, profile_id, body.name, body.description, body.params, body.confirm_risk
        )
        return _profile_out(session, profile)

    return _lab(call, session)


@app.post("/profiles/{profile_id}/activate")
def activate_profile(
    profile_id: int, session: DbSession, body: ActivateRequest | None = None
) -> dict[str, object]:
    def call():
        config = lab.activate_profile(session, profile_id, bool(body and body.confirm_risk))
        return {"profile_id": profile_id, "version": config.version}

    return _lab(call, session)


@app.delete("/profiles/{profile_id}")
def delete_profile(profile_id: int, session: DbSession) -> dict[str, object]:
    return _lab(lambda: lab.delete_profile(session, profile_id) or {"deleted": profile_id}, session)


class BacktestRequest(BaseModel):
    # A saved profile, a draft (params only), or a profile with unsaved changes (both).
    profile_id: int | None = None
    params: dict[str, Any] | None = None
    name: str | None = Field(default=None, max_length=80)
    start: date = lab.DEFAULT_START
    end: date | None = None
    capital: float = Field(default=20_000, gt=0, le=10_000_000)
    model: dict[str, Any] | None = None
    refresh_data: bool = False


@app.get("/backtests")
def get_backtests(session: DbSession) -> dict[str, object]:
    return {
        "runs": lab.list_runs(session),
        "cache": lab.cache_view(session),
        "model_fields": [{"key": k, "label": label} for k, label in lab.MODEL_SPECS],
        "model_defaults": lab.model_defaults(),
        "defaults": {
            "start": lab.DEFAULT_START.isoformat(),
            "end": market_today().isoformat(),
            "capital": settings.starting_capital,
        },
    }


@app.post("/backtests")
def create_backtest(body: BacktestRequest, session: DbSession) -> dict[str, object]:
    if body.profile_id is None and body.params is None:
        raise HTTPException(422, "Choisis un profil ou des paramètres.")

    def call():
        run = lab.queue_backtest(
            session,
            body.profile_id,
            body.params,
            body.start,
            body.end or market_today(),
            body.capital,
            body.model,
            body.refresh_data,
            body.name,
        )
        return lab.run_view(run)

    return _lab(call, session)


@app.get("/backtests/{run_id}")
def get_backtest(run_id: int, session: DbSession) -> dict[str, object]:
    return _lab(lambda: lab.run_view(lab.get_run(session, run_id), details=True), session)


@app.delete("/backtests/{run_id}")
def delete_backtest(run_id: int, session: DbSession) -> dict[str, object]:
    return _lab(lambda: lab.delete_run(session, run_id) or {"deleted": run_id}, session)
