from functools import lru_cache
from typing import Annotated

from fastapi import Depends, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.broker import Broker
from app.broker.alpaca import AlpacaBroker
from app.config import get_settings
from app.db import get_session
from app.models.enums import RejectReason
from app.services.trading import DecisionError, accept_opportunity, reject_opportunity

settings = get_settings()


@lru_cache
def get_broker() -> Broker:
    return AlpacaBroker.from_settings(settings)


DbSession = Annotated[Session, Depends(get_session)]
BrokerDep = Annotated[Broker, Depends(get_broker)]

app = FastAPI(title="Trading Advisor API", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
def health(session: DbSession) -> dict[str, str]:
    try:
        session.execute(text("SELECT 1"))
        database = "ok"
    except SQLAlchemyError:
        database = "indisponible"
    return {"status": "ok", "database": database, "broker_env": settings.broker_env}


class AcceptRequest(BaseModel):
    # Generated by the client once per click, so a double submit sends a single order.
    idempotency_key: str = Field(min_length=8, max_length=64)
    # Net credit per share; defaults to the screener's mid.
    limit_price: float | None = Field(default=None, gt=0)


class RejectRequest(BaseModel):
    idempotency_key: str = Field(min_length=8, max_length=64)
    reason: RejectReason
    note: str | None = Field(default=None, max_length=500)


@app.post("/opportunities/{opportunity_id}/accept")
def accept(
    opportunity_id: int, body: AcceptRequest, session: DbSession, broker: BrokerDep
) -> dict[str, object]:
    try:
        position = accept_opportunity(
            session,
            broker,
            opportunity_id,
            body.idempotency_key,
            settings.starting_capital,
            body.limit_price,
        )
    except DecisionError as exc:
        raise HTTPException(exc.status_code, str(exc)) from exc
    order = position.orders[0] if position.orders else None
    return {
        "position_id": position.id,
        "position_status": position.status.value,
        "order_status": order.status.value if order else None,
        "limit_price": float(order.limit_price) if order and order.limit_price else None,
    }


@app.post("/opportunities/{opportunity_id}/reject")
def reject(opportunity_id: int, body: RejectRequest, session: DbSession) -> dict[str, object]:
    try:
        decision = reject_opportunity(
            session, opportunity_id, body.idempotency_key, body.reason, body.note
        )
    except DecisionError as exc:
        raise HTTPException(exc.status_code, str(exc)) from exc
    return {"decision_id": decision.id, "reason": body.reason.value}
