"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-03 20:43:05.902022
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

ENUM_TYPES = (
    "strategy_type",
    "opportunity_status",
    "decision_action",
    "reject_reason",
    "option_type",
    "side",
    "position_status",
    "exit_reason",
    "order_purpose",
    "order_status",
    "position_event_type",
    "instrument_type",
)


revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_snapshots",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("equity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cash", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("collateral_used", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("buying_power", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("beta_weighted_delta", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("day", name=op.f("pk_account_snapshots")),
    )
    op.create_table(
        "iv_history",
        sa.Column("underlying", sa.String(length=16), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("iv30", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("hv30", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.PrimaryKeyConstraint("underlying", "day", name=op.f("pk_iv_history")),
    )
    op.create_table(
        "strategy_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_configs")),
        sa.UniqueConstraint("version", name=op.f("uq_strategy_configs_version")),
    )
    op.create_table(
        "screener_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_config_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("universe_size", sa.Integer(), nullable=True),
        sa.Column("filter_counts", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_config_id"],
            ["strategy_configs.id"],
            name=op.f("fk_screener_runs_strategy_config_id_strategy_configs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screener_runs")),
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("screener_run_id", sa.Integer(), nullable=False),
        sa.Column("strategy_config_id", sa.Integer(), nullable=False),
        sa.Column("underlying", sa.String(length=16), nullable=False),
        sa.Column("sector", sa.String(length=64), nullable=True),
        sa.Column(
            "strategy_type",
            sa.Enum("put_credit_spread", "cash_secured_put", "covered_call", name="strategy_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("proposed", "accepted", "rejected", "expired", name="opportunity_status"),
            nullable=False,
        ),
        sa.Column("expiration", sa.Date(), nullable=False),
        sa.Column("dte", sa.Integer(), nullable=False),
        sa.Column("underlying_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("credit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("max_loss", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("collateral", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("breakeven", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("short_delta", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("pop", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("iv_rank", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("iv_hv_ratio", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("aroc", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("score", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("next_earnings", sa.Date(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["screener_run_id"],
            ["screener_runs.id"],
            name=op.f("fk_opportunities_screener_run_id_screener_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_config_id"],
            ["strategy_configs.id"],
            name=op.f("fk_opportunities_strategy_config_id_strategy_configs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
    )
    op.create_index(
        op.f("ix_opportunities_screener_run_id"), "opportunities", ["screener_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_underlying"), "opportunities", ["underlying"], unique=False
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.Enum("accept", "reject", name="decision_action"), nullable=False),
        sa.Column(
            "reject_reason",
            sa.Enum(
                "premium_too_low",
                "sector_concentration",
                "no_conviction",
                "news",
                "other",
                name="reject_reason",
            ),
            nullable=True,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_decisions_opportunity_id_opportunities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_decisions_idempotency_key")),
        sa.UniqueConstraint("opportunity_id", name=op.f("uq_decisions_opportunity_id")),
    )
    op.create_table(
        "opportunity_legs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("option_symbol", sa.String(length=32), nullable=False),
        sa.Column("option_type", sa.Enum("put", "call", name="option_type"), nullable=False),
        sa.Column("side", sa.Enum("buy", "sell", name="side"), nullable=False),
        sa.Column("strike", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("bid", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("ask", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("delta", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("open_interest", sa.Integer(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_opportunity_legs_opportunity_id_opportunities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_legs")),
    )
    op.create_index(
        op.f("ix_opportunity_legs_opportunity_id"),
        "opportunity_legs",
        ["opportunity_id"],
        unique=False,
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=True),
        sa.Column("parent_position_id", sa.Integer(), nullable=True),
        sa.Column("underlying", sa.String(length=16), nullable=False),
        sa.Column("sector", sa.String(length=64), nullable=True),
        sa.Column(
            "strategy_type",
            sa.Enum("put_credit_spread", "cash_secured_put", "covered_call", name="strategy_type"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "open", "closed", "expired", "assigned", name="position_status"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entry_credit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("exit_debit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("collateral", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("max_loss", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "exit_reason",
            sa.Enum(
                "profit_target",
                "stop_loss",
                "time_exit",
                "manual",
                "expiration",
                "assignment",
                "called_away",
                name="exit_reason",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_positions_opportunity_id_opportunities"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_position_id"],
            ["positions.id"],
            name=op.f("fk_positions_parent_position_id_positions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index(op.f("ix_positions_underlying"), "positions", ["underlying"], unique=False)
    op.create_table(
        "shadow_outcomes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("pnl", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("exit_reason", sa.String(length=32), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_shadow_outcomes_opportunity_id_opportunities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shadow_outcomes")),
        sa.UniqueConstraint("opportunity_id", name=op.f("uq_shadow_outcomes_opportunity_id")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "open",
                "take_profit",
                "stop_loss",
                "time_exit",
                "manual_close",
                name="order_purpose",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "submitted",
                "partially_filled",
                "filled",
                "canceled",
                "rejected",
                "expired",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("time_in_force", sa.String(length=8), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("quote_bid", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("quote_ask", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_orders_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("broker_order_id", name=op.f("uq_orders_broker_order_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_orders_idempotency_key")),
    )
    op.create_index(op.f("ix_orders_position_id"), "orders", ["position_id"], unique=False)
    op.create_table(
        "position_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "opened",
                "take_profit_placed",
                "stop_triggered",
                "time_exit_triggered",
                "closed",
                "expired",
                "assigned",
                "called_away",
                "reconciliation_mismatch",
                name="position_event_type",
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_position_events_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_events")),
    )
    op.create_index(
        op.f("ix_position_events_position_id"), "position_events", ["position_id"], unique=False
    )
    op.create_table(
        "position_legs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column(
            "instrument_type", sa.Enum("option", "stock", name="instrument_type"), nullable=False
        ),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("option_type", sa.Enum("put", "call", name="option_type"), nullable=True),
        sa.Column("strike", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("expiration", sa.Date(), nullable=True),
        sa.Column("side", sa.Enum("buy", "sell", name="side"), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_position_legs_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_legs")),
    )
    op.create_index(
        op.f("ix_position_legs_position_id"), "position_legs", ["position_id"], unique=False
    )
    op.create_table(
        "position_marks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("marked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mark", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("delta", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("unrealized_pnl", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_position_marks_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_marks")),
    )
    op.create_index(
        op.f("ix_position_marks_marked_at"), "position_marks", ["marked_at"], unique=False
    )
    op.create_index(
        op.f("ix_position_marks_position_id"), "position_marks", ["position_id"], unique=False
    )
    op.create_table(
        "fills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.Enum("buy", "sell", name="side"), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("fees", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
    )
    op.create_index(op.f("ix_fills_order_id"), "fills", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fills_order_id"), table_name="fills")
    op.drop_table("fills")
    op.drop_index(op.f("ix_position_marks_position_id"), table_name="position_marks")
    op.drop_index(op.f("ix_position_marks_marked_at"), table_name="position_marks")
    op.drop_table("position_marks")
    op.drop_index(op.f("ix_position_legs_position_id"), table_name="position_legs")
    op.drop_table("position_legs")
    op.drop_index(op.f("ix_position_events_position_id"), table_name="position_events")
    op.drop_table("position_events")
    op.drop_index(op.f("ix_orders_position_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("shadow_outcomes")
    op.drop_index(op.f("ix_positions_underlying"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_opportunity_legs_opportunity_id"), table_name="opportunity_legs")
    op.drop_table("opportunity_legs")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_opportunities_underlying"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_screener_run_id"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_table("screener_runs")
    op.drop_table("strategy_configs")
    op.drop_table("iv_history")
    op.drop_table("account_snapshots")
    # ### end Alembic commands ###
    for name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {name}")
